---
title: "Intro to Quarto Exercise Instructions"
author: "U.S. Fish and Wildlife Service"
date-modified: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
---

## Exercise overview

The objective of this series of exercises is to expose you to the many features of Quarto documents through the example of a Western Snowy Plover survey. The exercises will step you through the key elements of Quarto documents and provide you with an opportunity to explore the various components and features that will enable you to create quality documents that effectively communicate and document your analyses and findings.

## Outline

In this training course, we will guide you through three exercises to enhance your familiarity with Quarto documents. The first exercise focuses on understanding **YAML headers**, where you'll learn to customize metadata such as title and author. Next, you'll dive into the **document body**, exploring formatting options to organize your content effectively. Finally, you'll master **code chunks**, allowing you to embed and execute code in R, Python, or Julia, creating dynamic reports that showcase your analysis. Through these exercises, you'll develop essential skills to create professional and polished Quarto documents.

## Exercise 1: YAML metadata

A **YAML** (**Y**et **A**nother **M**arkup **L**anguage) header is a crucial component of Quarto documents that defines metadata for the document, typically enclosed within a pair of triple-dashed lines at the beginning of the file. It allows users to specify important information such as the document's title, author, date, and output formats (like HTML, PDF, or Word). Additionally, YAML headers can include parameters to control formatting options and customize the behavior of the document, such as including bibliographies or setting specific themes. By using a YAML header, authors can ensure that their documents are well-organized and professionally presented.

### Set up 
- Start by opening your "intro-to-quarto-exercersis.Rproj" in RStudio. 

- Open the "Snow_Plover_Exercise.qmd" located in the "Exercise" directory.

### Tasks to accomplish
- Update the title from "Help" to "Annual Western Snowy Plover Survey"

- Change text in the author section from "Your Name" to your name 

## Exercise 2: Document body

## Exercise 3: Code chunks
